server.port=8083
spring.application.name=application-service
spring.data.mongodb.uri=mongodb://localhost:27017/applicationdb
app.jwt.secret=jobPortalSecretKey2024VeryLongSecretKeyForSecurity

# Feign Client - calls Job Service directly
job.service.url=http://localhost:8082

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
