server.port=8081
spring.application.name=auth-service
spring.data.mongodb.uri=mongodb://localhost:27017/authdb
app.jwt.secret=jobPortalSecretKey2024VeryLongSecretKeyForSecurity
app.jwt.expiration=86400000
